apiVersion: v1
kind: ConfigMap
metadata:
  name: conform-config
  labels:
    {{- include "conform.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
